export const symbolsData = {
  "BORSA ISTANBUL": [
    "THYAO", "ASELS", "EREGL", "SISE", "AKBNK", "YKBNK", "GARAN", "KCHOL", "SAHOL", "TUPRS", "BIMAS", "ISCTR", "PETKM", "KOZAL", "KRDMD", "HEKTS", "SASA", "KONTR", "EUPWR", "ASTOR", "GESAN", "SMART", "ODAS", "TCELL", "TTKOM", "ENKAI", "FROTO", "TOASO", "OTKAR", "VESTL", "ARCLK", "BEKO", "TAVHL", "PGSUS", "ULKER", "MGROS", "SOKM", "AEFES", "CCOLA", "AGHOL", "DOHOL", "TEKFEN", "ALARK", "GUBRF", "KOZAA", "IPEKE", "MAVI", "YATAS", "VAKBN", "HALKB", "TSKB", "SKBNK", "ISMEN", "ISGYO", "EKGYO", "TRGYO", "AKSEN", "ZOREN", "AYDEM", "GWIND", "CANTE", "SMRTG", "ALFAS", "MIATK", "YEOTK", "PENTA", "LOGO", "NETAS", "KAREL", "INDES", "DGATE", "DESPC", "LINK", "FONET", "KFEIN", "ARDYZ", "VBTYZ", "SDTTR", "ONCSM", "CVKMD", "KOPOL", "EGEEN", "BRYAT", "BFREN", "KONYA", "KARTN", "GOLTS", "CIMSA", "AKCNS", "BUCIM", "NUHCM", "CMBTN", "BSOKE", "BTCIM", "AFYON", "KUTPO", "KLKIM", "DMSAS", "CEMTS", "PARSN", "DITAS", "JANTS", "KATMR", "TUKAS", "TATGD", "PNSUT", "PETUN", "BANVT", "KNFRT", "KUTPO", "KLMSN", "ALCAR", "DURDO", "GOODY", "BRISA", "LIDER", "HLGYO", "OZKGY", "RYGYO", "PAGYO", "ISFIN", "SELEC", "DEVA", "GENIL", "TRILC", "MEDTR", "LKMNH", "MPARK", "GLYHO", "VERUS", "VERTU", "INVEO", "HEDEF", "GSDHO", "METRO", "IHLAS", "IEYHO", "IHGZT", "IHAAS", "ZEDUR", "HUNER", "BIOEN", "CONSE", "ESEN", "NATEN", "MAGEN", "KARYE", "AYEN", "AKENR", "ODAS"
  ],
  "ENDEKSLER": [
    "XU100",  // BIST 100
    "XU030",  // BIST 30
    "XBANK",  // BIST BANKA
    "XSINA",  // BIST SINAI
    "NDX",    // NASDAQ 100 (US100)
    "SPX",    // S&P 500 (US500)
    "DJI",    // DOW JONES (US30)
    "DAX",    // GERMANY 30 (DAX)
    "UKX",    // FTSE 100 (UK100)
    "CAC40",  // FRANCE 40
    "NI225",  // NIKKEI 225
    "SZSE",   // SHENZHEN
    "HSI"     // HANG SENG
  ],
  "EMTIA": [
    "XAUUSD", // ONS ALTIN
    "XAGUSD", // ONS GUMUS
    "GLDGR",  // GRAM ALTIN (BIST)
    "BRENT",  // BRENT PETROL
    "USOIL",  // WTI PETROL
    "NG1!",   // DOGALGAZ
    "COPPER", // BAKIR
    "PLATINUM",
    "PALLADIUM",
    "CORN",   // MISIR
    "WHEAT",  // BUGDAY
    "SOYBEAN",// SOYA
    "SUGAR",  // SEKER
    "COFFEE", // KAHVE
    "COTTON"  // PAMUK
  ],
  "EXCHANGE": [
    "USDTRY", "EURTRY", "GBPTRY", "EURUSD", "GBPUSD", "USDJPY", "USDCHF", "USDCAD", "AUDUSD", "NZDUSD", "EURGBP", "EURJPY", "GBPJPY", "AUDJPY", "CADJPY", "CHFJPY", "EURAUD", "EURCAD", "EURCHF", "GBPAUD", "GBPCAD", "AUDCAD", "AUDCHF", "NZDJPY", "AUDNZD", "XAUUSD", "XAGUSD"
  ],
  "KRIPTO": [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "ADAUSDT", "AVAXUSDT", "DOGEUSDT", "SHIBUSDT", "DOTUSDT", "LINKUSDT", "TRXUSDT", "MATICUSDT", "LTCUSDT", "BCHUSDT", "UNIUSDT", "XLMUSDT", "ATOMUSDT", "XMRUSDT", "ETCUSDT", "FILUSDT", "HBARUSDT", "APTUSDT", "ARBUSDT", "OPUSDT", "INJUSDT", "RNDRUSDT", "GRTUSDT", "MKRUSDT", "STXUSDT", "RUNEUSDT", "NEARUSDT", "ALGOUSDT", "AAVEUSDT", "FTMUSDT", "SANDUSDT", "GALAUSDT", "MANAUSDT", "EGLDUSDT", "EOSUSDT", "THETAUSDT", "AXSUSDT", "XTZUSDT", "FLOWUSDT", "KAVAUSDT", "MINAUSDT", "QNTUSDT", "CHZUSDT", "NEOUSDT", "JASMYUSDT", "PEPEUSDT", "FLOKIUSDT", "BONKUSDT", "WIFUSDT", "1000SATSUSDT", "FETUSDT", "AGIXUSDT", "OCEANUSDT", "CFXUSDT", "FXSUSDT", "LDOUSDT", "SSVUSDT", "SUIUSDT", "SEIUSDT", "TIAUSDT", "ORDIUSDT", "BLURUSDT", "MEMEUSDT"
  ],
  "STOCKS": [
    "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "TSLA", "META", "NFLX", "AMD", "INTC", "IBM", "ORCL", "CSCO", "CRM", "ADBE", "PYPL", "V", "MA", "JPM", "BAC", "WFC", "C", "GS", "MS", "BA", "DIS", "KO", "PEP", "MCD", "SBUX", "NKE", "WMT", "TGT", "COST", "PG", "JNJ", "PFE", "MRK", "ABBV", "LLY", "UNH", "XOM", "CVX", "COP", "SLB", "GE", "F", "GM", "TM", "HMC", "SONY", "TMUS", "VZ", "T"
  ]
};
