export const symbolsData = {
  "BORSA ISTANBUL": [
    "THYAO", "ASELS", "EREGL", "SISE", "AKBNK", "YKBNK", "GARAN", "KCHOL", "SAHOL", "TUPRS", "BIMAS", "ISCTR", "PETKM", "KOZAL", "KRDMD", "HEKTS", "SASA", "KONTR", "EUPWR", "ASTOR", "GESAN", "SMART", "ODAS", "TCELL", "TTKOM", "ENKAI", "FROTO", "TOASO", "OTKAR", "VESTL", "ARCLK", "TAVHL", "PGSUS", "ULKER", "MGROS", "SOKM", "AEFES", "CCOLA", "AGHOL", "DOHOL", "TEKFEN", "ALARK", "GUBRF", "KOZAA", "IPEKE", "MAVI", "YATAS", "VAKBN", "HALKB", "TSKB", "SKBNK", "ISMEN", "ISGYO", "EKGYO", "TRGYO", "AKSEN", "ZOREN", "AYDEM", "GWIND", "CANTE", "SMRTG", "ALFAS", "MIATK", "YEOTK", "PENTA", "LOGO", "NETAS", "KAREL", "INDES", "DGATE", "DESPC", "LINK", "FONET", "KFEIN", "ARDYZ", "VBTYZ", "SDTTR", "ONCSM", "CVKMD", "KOPOL", "EGEEN", "BRYAT", "BFREN", "KONYA", "KARTN", "GOLTS", "CIMSA", "AKCNS", "BUCIM", "NUHCM", "CMBTN", "BSOKE", "BTCIM", "AFYON", "KUTPO", "KLKIM", "DMSAS", "CEMTS", "PARSN", "DITAS", "JANTS", "KATMR", "TUKAS", "TATGD", "PNSUT", "PETUN", "BANVT", "KNFRT", "KLMSN", "ALCAR", "DURDO", "GOODY", "BRISA", "LIDER", "HLGYO", "OZKGY", "RYGYO", "PAGYO", "ISFIN", "SELEC", "DEVA", "GENIL", "TRILC", "MEDTR", "LKMNH", "MPARK", "GLYHO", "VERUS", "VERTU", "INVEO", "HEDEF", "GSDHO", "METRO", "IHLAS", "IEYHO", "IHGZT", "IHAAS", "ZEDUR", "HUNER", "BIOEN", "CONSE", "ESEN", "NATEN", "MAGEN", "KARYE", "AYEN", "AKENR"
  ],
  "ENDEKSLER": [
    "XU100",
    "XU030",
    "XBANK",
    "XSINA",
    "NDX",
    "SPX",
    "DJI",
    "DAX",
    "UKX",
    "CAC40",
    "NI225",
    "SZSE",
    "HSI"
  ],
  "EMTIA": [
    "XAUTRY",
    "XAGTRY",
    "GLDGR",
    "BRENT",
    "USOIL",
    "NG1!",
    "COPPER",
    "PLATINUM",
    "PALLADIUM",
    "CORN",
    "WHEAT",
    "SOYBEAN",
    "SUGAR",
    "COFFEE",
    "COTTON"
  ],
  "EXCHANGE": [
    "USDTRY", "EURTRY", "GBPTRY", "EURUSD", "GBPUSD", "USDJPY", "USDCHF", "USDCAD", "AUDUSD", "NZDUSD", "EURGBP", "EURJPY", "GBPJPY", "AUDJPY", "CADJPY", "CHFJPY", "EURAUD", "EURCAD", "EURCHF", "GBPAUD", "GBPCAD", "AUDCAD", "AUDCHF", "NZDJPY", "AUDNZD", "XAUUSD", "XAGUSD"
  ],
  "KRIPTO": [
    "BTCTRY", "ETHTRY", "SOLTRY", "BNBTRY", "XRPTRY", "ADATRY", "AVAXTRY", "DOGETRY", "SHIBTRY", "DOTTRY", "LINKTRY", "TRXTRY", "POLTRY", "LTCTRY", "BCHTRY", "UNITRY", "XLMTRY", "ATOMTRY", "ETCTRY", "FILTRY", "HBARTRY", "APTTRY", "ARBTRY", "OPTRY", "INJTRY", "RENDERTRY", "GRTTRY", "STXTRY", "NEARTRY", "ALGOTRY", "AAVETRY", "SANDTRY", "GALATRY", "MANATRY", "EGLDTRY", "THETATRY", "AXSTRY", "XTZTRY", "MINATRY", "CHZTRY", "NEOTRY", "JASMYTRY", "PEPETRY", "FLOKITRY", "BONKTRY", "WIFTRY", "1000SATSTRY", "FETTRY", "CFXTRY", "SUITRY", "SEITRY", "TIATRY", "ORDITRY", "BLURTRY", "MEMETRY"
  ],
  "STOCKS": [
    "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "TSLA", "META", "NFLX", "AMD", "INTC", "IBM", "ORCL", "CSCO", "CRM", "ADBE", "PYPL", "V", "MA", "JPM", "BAC", "WFC", "C", "GS", "MS", "BA", "DIS", "KO", "PEP", "MCD", "SBUX", "NKE", "WMT", "TGT", "COST", "PG", "JNJ", "PFE", "MRK", "ABBV", "LLY", "UNH", "XOM", "CVX", "COP", "SLB", "GE", "F", "GM", "TM", "HMC", "SONY", "TMUS", "VZ", "T"
  ]
};
